### PR TITLE
Task 3

### PR DESCRIPTION
**Pull request by Shawn0604**
蔡尚峰
http://54.196.142.222:8000/
http://54.196.142.222:8000/attraction/10

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Cannot connect to attraction page from links on homepage.
- Take attention on block margin and text alignment.
52 202 64 48_8000_attraction_15

**Comment by Shawn0604** [comment]
已修正，再麻煩老師查看

**Review by cwpeng — CHANGES_REQUESTED** [review]
Layout width exceeds screen width in middle size of devices.
54 196 142 222_8000_attraction_10

**Comment by Shawn0604** [comment]
已再次修正，再麻煩老師查看

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
