### PR TITLE
作業一

### PR DESCRIPTION
**Pull request by Shawn0604**
蔡尚峰
http://52.202.64.48:8000/api/attractions?page=1
http://52.202.64.48:8000/api/attractions?page=0&keyword=劍潭
http://52.202.64.48:8000/api/attractions?page=0&keyword=北
http://52.202.64.48:8000/api/attraction/10
http://52.202.64.48:8000/api/mrts

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Cannot connect to your server.

**Comment by Shawn0604** [comment]
已修正，再麻煩老師查看

**Review by cwpeng — CHANGES_REQUESTED** [review]
images field should not be an empty array.

**Comment by Shawn0604** [comment]
已經再次修正，再麻煩老師查看

**Comment by cwpeng** [comment]
Cannot connect to your server. You should always keep server alive.

**Comment by Shawn0604** [comment]
已經重新啟動，再麻煩老師查看

**Comment by cwpeng** [comment]
Because your server is down many times, there should be fatal problem, you should not just restart, you have to solve the root problem. So, tell me, what you have done different from before, to make your server run permanantly?

This is the final part of task 1. You should follow.

**Comment by Shawn0604** [comment]
我使用nohup uvicorn app:app --host 0.0.0.0 --port 8000 --reload來執行，讓server可以一直運作，再麻煩老師查看，謝謝老師

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
